site_name: Ontitansshoulder's Blog
site_author: Zhongkai Liu
site_description: >-
  A collection of notes I took during my learning...

# theme config
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra_css:
  - css/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Notes:
    - Welcome: "index.md"
    - Cloud and Containers:
      - Docker:
        - "Cloud-and-Containers/Docker/Docker-Knowledge.md"
      - k8s:
        - "Cloud-and-Containers/k8s/K8s-Knowledge.md"
        - "Cloud-and-Containers/k8s/service_mesh.md"
    - Dev Tools Reference:
      - Splunk:
        - "Dev-Tools-Reference/Splunk/Splunk-References.md"
        - "Dev-Tools-Reference/Splunk/Splunk-Dashboarding.md"
    - Linux:
      - Concepts:
        - Linux Foundation: "Linux/Concepts/Linux_Foundation.md"
        - Linux System Administration: "Linux/Concepts/Linux_Foundation_System_Admin.md"
        - Linux Network Administration: "Linux/Concepts/Linux_Foundation_Network_Admin.md"
      - Commands:
        - Freq Used Shell Cmds: "Linux/Commands/Freq-Used-Shell-Cmds.md"
        - Freq Used Network Cmds: "Linux/Commands/Networking-Shell-Cmds.md"
        - Text Manipulating Cmds: "Linux/Commands/Text-Manipulating-Cmds.md"
      - References:
        - Freq Linux Tasks: "Linux/References/Freq-Tasks.md"
        - Linux Terminal Tricks: "Linux/References/Terminal-Tricks.md"
        - Vim Tricks: "Linux/References/Vim-Tricks.md"
        - Manage Accounts & Groups: "Linux/References/Account-Administration.md"
    - Programming Lang Reference:
      - Golang:
        - Golang Language Reference: "Programming-Lang-Reference/Golang/Golang-Specs.markdown"
        - Effective Go: "Programming-Lang-Reference/Golang/Best-Practices.md"
        - Go libraries and examples: "Programming-Lang-Reference/Golang/Freq-Used-Libs.md"
      - Java:
        - Effective Java: "Programming-Lang-Reference/Java/Best-Practices.md"
        - Java Design Patterns: "Programming-Lang-Reference/Java/Design-Patterns.md"
        - Testing Design Patterns: "Programming-Lang-Reference/Java/Testing-Design-Patterns.md"
      - Perl:
        - Perl Language Reference: "Programming-Lang-Reference/Perl/Perl-Lang-Specs.md"
      - Shell:
        - Shell Scripting: "Programming-Lang-Reference/Shell/Shell-Scripting.md"
      - Github Markdown Guide: "Programming-Lang-Reference/Github-Markdown.md"
      - Regex Cheatsheet: "Programming-Lang-Reference/Regex-Specs.md"
    - Other Reading Notes:
      - How Netflix Works: "Reading-Notes/How-Netflix-Works.md"
      - System Design Guide: "Reading-Notes/System-Design-Concepts.md"
      - Why Latency Matters: "Reading-Notes/Why-Latency-Matters.md"
      - Intro to DevOps and SRE: "Reading-Notes/DevOps_SRE.md"
      - Leading Without Formal Authority: "Reading-Notes/Leading-without-formal-authority.md"